    __default__:
    q:  broad
    h_vmem: 32G          # Requested memory per job
    h_rt:   30:0:0       # Requested runtime
    pe: mpi 4            # Use 4 cores for the MPI environment, adjust accordingly
    binding:    linear:4 # Linear binding with 4 slots


