__default__:
    q:  broad
    h_vmem: 40G
    h_rt:   300:0:0
    pe: smp 6
    binding:    linear:1

LearnReadOrientationModel:
    q:  broad
    h_vmem: 30G
    h_rt:   300:0:0
    pe: smp 8
    binding:    linear:1
